In [91]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [92]:
import numpy as np
print(np.__version__)

2.1.1


In [93]:
#Create a NumPy array containing the numbers from 0 to 9

my_lst = [1,2,3,4,5,6,7,8,9]

import numpy as np  # Import NumPy with alias np

arr = np.array(my_lst)

# Check type of the array
print(type(arr))  # This will output: <class 'numpy.ndarray'>

# Print the array
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [94]:
#Create a NumPy array containing the numbers from 1 to 9
my_lst = [1,2,3,4,5,6,7,8,9]

arr = np.array(my_lst)

#check the shape  of the array
shape = arr.shape

#check the data type of the array
data_type = arr.dtype

# Print the shape, data type, and the array itself
print("Array:", arr)
print("Shape:", shape) 
print("Data type:", data_type) 


Array: [1 2 3 4 5 6 7 8 9]
Shape: (9,)
Data type: int64


In [95]:
# Create a 2D array with shape (3, 4) filled with integers between 0 and 10
my_lst1 = [1,2,3,4]
my_lst2 = [4,6,7,8]
my_lst3 = [0,9,1,2]

arr = np.array([my_lst1,my_lst2,my_lst3])

#check the shape  of the array
shape = arr.shape

#check the data type of the array
data_type = arr.dtype

# Print the shape, data type, and the array itself
print("Array:\n", arr)
print("Shape:", shape) 
print("Data type:", data_type) 


Array:
 [[1 2 3 4]
 [4 6 7 8]
 [0 9 1 2]]
Shape: (3, 4)
Data type: int64


In [96]:
#Given the array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]), reshape it into a 2x4 matrix.
my_lst = [1,2,3,4,5,6,7,8]

arr = np.array(my_lst)

#check to reshape the array into 2x4 matrix

reshaped_arr = arr.reshape(2, 4)

print("reshaped arr:\n", reshaped_arr)

reshaped arr:
 [[1 2 3 4]
 [5 6 7 8]]


In [97]:
import numpy as np

# Given 2D array
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Extract the element in the 2nd row and 3rd column
element = arr[1, 2]

# Print the extracted element
print("Element in the 2nd row and 3rd column:", element)

Element in the 2nd row and 3rd column: 6


In [98]:
import numpy as np

#Given 2D array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#Extract the element in the 2nd row and 2nd column
element = arr[2,2]

#print the extracted element
print("Element in the 2nd row and 2nd column:", element)

Element in the 2nd row and 2nd column: 9


In [99]:
import numpy as np

#Given 3D array
arr = np.array([[1,2,3, 4],
                [5,6,7,8],
                [9,10,11, 12],
                [13,14,15,16]])

#Extract the element in the 3rd row and 3rd column
element = arr[3,3]

#print the extracted element
print("Element in the 3rd row and 3rd column:", element)

Element in the 3rd row and 3rd column: 16


In [100]:
import numpy as np

# Given 1D array using np.arange
arr = np.arange(10)  # This creates an array with elements from 0 to 9

# Extract elements from index 2 to index 6 (not inclusive)
extracted_elements = arr[2:6]

# Print the original array and the extracted elements
print("Original Array:", arr)
print("Extracted Elements (index 2 to index 6):", extracted_elements)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Extracted Elements (index 2 to index 6): [2 3 4 5]


In [101]:
#Element-Wise Operations

#create two Numpy arrays,
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

Val = 2

addition = arr1 + arr2

subtraction = arr1 - arr2

multiplication = arr1 * arr2

#exploratory data analysis

#Perform element-wise addition, subtraction, and multiplication
#print the results

print("Array 1:", arr1)
print("Array2:", arr2)
print("element-wise addition:", addition)
print("element-wise subtraction:", subtraction)
print("element-wise multiplication:", multiplication)


Array 1: [1 2 3]
Array2: [4 5 6]
element-wise addition: [5 7 9]
element-wise subtraction: [-3 -3 -3]
element-wise multiplication: [ 4 10 18]


In [102]:
import numpy as np

#Given array
arr = np.array ([1, 2, 3, 4, 5])

# Add scalar value 10 to each element of the array using broadcasting
result = arr + 10
# Print the original array and the result
print("Original Array:", arr)
print("Array after adding 10 to each element:", result)
               

Original Array: [1 2 3 4 5]
Array after adding 10 to each element: [11 12 13 14 15]


In [103]:
#Create a NumPy array of 15 random integers between 0 and 50. Find the mean, median, and standard deviation of the array

# Create a NumPy array of 15 random integers between 0 and 50
arr = np.random.randint(0, 51, size=15)

# Calculate the mean, median, and standard deviation
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

# Print the results
print("Array:", arr)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Array: [47 24  8 42  6  1 39 50 20  4  8 15 22  6 31]
Mean: 21.533333333333335
Median: 20.0
Standard Deviation: 16.128098324215273


In [104]:
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Extract elements greater than 25
extracted_elements = arr[arr > 25]

# Print the result
print("Original Array:", arr)
print("Elements greater than 25:", extracted_elements)

Original Array: [10 20 30 40 50]
Elements greater than 25: [30 40 50]


In [105]:
#Create two arrays 
arr1 = np.array([1, 2, 3]) 
arr2 = np.array([4, 5, 6])
#Concatenate them into a single array
concatenated_array = np.concatenate((arr1, arr2))

# Print the result
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Concatenated Array:", concatenated_array)

Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenated Array: [1 2 3 4 5 6]


In [106]:
import pandas as pd

# Sample dictionary
data = {
    "Name": ["San", "Jane", "Doe"],
    "Age": [28, 34, 29],
    "Department": ["HR", "IT", "Finance"]
}

# Task 1: Create and display the DataFrame
df = pd.DataFrame(data)
print("DataFrame:")
print(df)

# Task 2: Save the DataFrame as "data.csv"
df.to_csv("data.csv", index=False)

# Confirmation message
print("\nDataFrame saved as 'data.csv'.")


DataFrame:
   Name  Age Department
0   San   28         HR
1  Jane   34         IT
2   Doe   29    Finance

DataFrame saved as 'data.csv'.


In [107]:
import pandas as pd

# Task 1: Read the CSV file into a DataFrame
df = pd.read_csv("data.csv")

# Task 2: Display the first 5 rows of the DataFrame
print("First 5 rows of the DataFrame:")
print(df.head())


First 5 rows of the DataFrame:
   Name  Age Department
0   San   28         HR
1  Jane   34         IT
2   Doe   29    Finance


In [108]:
import pandas as pd

# Task 1: Read the CSV file into a DataFrame
df = pd.read_csv("data.csv")

# Task 2: Select and display the "Name" column
print("Name column:")
print(df["Name"])


Name column:
0     San
1    Jane
2     Doe
Name: Name, dtype: object


In [109]:
#Length of values (4) does not match length of index (3), indicates that you're trying to add a new column with 4 values to a DataFrame that currently has only 3 rows.
#The number of elements you add to a column must match the number of rows in the DataFrame. Since your DataFrame is created from data.csv, which is initially defined with 3 entries, should provide 3 salary values instead of 4.

In [110]:
import pandas as pd

# Task 1: Read the CSV file into a DataFrame
df = pd.read_csv("data.csv")

# Task 2: Add a new column "Salary" to the DataFrame
df["Salary"] = [50000, 60000, 70000]

# Task 3: Display the updated DataFrame
print("Updated DataFrame with 'Salary' column:")
print(df)

Updated DataFrame with 'Salary' column:
   Name  Age Department  Salary
0   San   28         HR   50000
1  Jane   34         IT   60000
2   Doe   29    Finance   70000
