In [12]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [13]:
import numpy as np
print(np.__version__)

2.1.1


In [14]:
#Create a NumPy array containing the numbers from 0 to 9

my_lst = [1,2,3,4,5,6,7,8,9]

import numpy as np  # Import NumPy with alias np

arr = np.array(my_lst)

# Check type of the array
print(type(arr))  # This will output: <class 'numpy.ndarray'>

# Print the array
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [15]:
#Create a NumPy array containing the numbers from 1 to 9
my_lst = [1,2,3,4,5,6,7,8,9]

arr = np.array(my_lst)

#check the shape  of the array
shape = arr.shape

#check the data type of the array
data_type = arr.dtype

# Print the shape, data type, and the array itself
print("Array:", arr)
print("Shape:", shape) 
print("Data type:", data_type) 


Array: [1 2 3 4 5 6 7 8 9]
Shape: (9,)
Data type: int64


In [16]:
# Create a 2D array with shape (3, 4) filled with integers between 0 and 10
my_lst1 = [1,2,3,4]
my_lst2 = [4,6,7,8]
my_lst3 = [0,9,1,2]

arr = np.array([my_lst1,my_lst2,my_lst3])

#check the shape  of the array
shape = arr.shape

#check the data type of the array
data_type = arr.dtype

# Print the shape, data type, and the array itself
print("Array:\n", arr)
print("Shape:", shape) 
print("Data type:", data_type) 


Array:
 [[1 2 3 4]
 [4 6 7 8]
 [0 9 1 2]]
Shape: (3, 4)
Data type: int64


In [17]:
#Given the array arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]), reshape it into a 2x4 matrix.
my_lst = [1,2,3,4,5,6,7,8]

arr = np.array(my_lst)

#check to reshape the array into 2x4 matrix

reshaped_arr = arr.reshape(2, 4)

print("reshaped arr:\n", reshaped_arr)

reshaped arr:
 [[1 2 3 4]
 [5 6 7 8]]


In [18]:
import numpy as np

# Given 2D array
arr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Extract the element in the 2nd row and 3rd column
element = arr[1, 2]

# Print the extracted element
print("Element in the 2nd row and 3rd column:", element)

Element in the 2nd row and 3rd column: 6


In [19]:
import numpy as np

#Given 2D array
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#Extract the element in the 2nd row and 2nd column
element = arr[2,2]

#print the extracted element
print("Element in the 2nd row and 2nd column:", element)

Element in the 2nd row and 2nd column: 9


In [20]:
import numpy as np

#Given 3D array
arr = np.array([[1,2,3, 4],
                [5,6,7,8],
                [9,10,11, 12],
                [13,14,15,16]])

#Extract the element in the 3rd row and 3rd column
element = arr[3,3]

#print the extracted element
print("Element in the 3rd row and 3rd column:", element)

Element in the 3rd row and 3rd column: 16


In [21]:
import numpy as np

# Given 1D array using np.arange
arr = np.arange(10)  # This creates an array with elements from 0 to 9

# Extract elements from index 2 to index 6 (not inclusive)
extracted_elements = arr[2:6]

# Print the original array and the extracted elements
print("Original Array:", arr)
print("Extracted Elements (index 2 to index 6):", extracted_elements)

Original Array: [0 1 2 3 4 5 6 7 8 9]
Extracted Elements (index 2 to index 6): [2 3 4 5]


In [25]:
#Element-Wise Operations

#create two Numpy arrays,
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

Val = 2

#addition = arr1 + arr2

#subtraction = arr1 - arr2

#multiplication = arr1 * arr2

#exploratory data analysis

arr*2
arr+2
arr-2

#Perform element-wise addition, subtraction, and multiplication
#print the results

print("Array 1:", arr1)
print("Array2:", arr2)
print("element-wise addition:", addition)
print("element-wise subtraction:", subtraction)
print("element-wise multiplication:", multiplication)


Array 1: [1 2 3]
Array2: [4 5 6]
element-wise addition: [5 7 9]
element-wise subtraction: [-3 -3 -3]
element-wise multiplication: [ 4 10 18]
